---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nginx-nextcloud-{{ template "nextcloud.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "nextcloud.name" . }}
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: nginx-{{ template "nextcloud.fullname" . }}:latest
  source:
    git:
      uri: "https://github.com/ycornamusaz/docker-nginx-fpm"
    type: Git
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: nginx-nextcloud-{{ template "nextcloud.fullname" . }}:latest
