---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "nextcloud.name" . }}
  name: {{ template "nextcloud.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nginx
        from:
          kind: ImageStreamTag
          name: nginx-nextcloud-{{ template "nextcloud.fullname" . }}:latest
  template:
    metadata:
      labels:
        app: {{ template "nextcloud.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:13.0.7-fpm
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
          securityContext:
            capabilities: {}
            privileged: false
          volumeMounts:
            - name: data
              mountPath: /var/www/html
            - name: config
              mountPath: /usr/src/nextcloud/config/
          resources: {}
          capabilities: {}
          env:
            - name: POSTGRES_HOST
              value: 127.0.0.1

            - name: POSTGRES_DB
              {{- if .Values.nextcloud.Db.Name }}
              value: {{ .Values.nextcloud.Db.Name }}
              {{- else }}
              value: {{ template "nextcloud.name" . }}
              {{- end }}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: dbUsername

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: dbPassword

            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: appUsername

            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: appPassword

            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ .Values.nextcloud.TrustedDomains | quote }}

          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            timeoutSeconds: 1

        - name: nginx
          image: ""
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              protocol: TCP

          securityContext:
            capabilities: {}
            privileged: false

          resources: {}

          volumeMounts:
            - name: data
              mountPath: /var/www/html
              readOnly: true

          capabilities: {}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1

        - name: postgres
          image: centos/postgresql-96-centos7
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432
              protocol: TCP

          securityContext:
            capabilities: {}
            privileged: false

          resources: {}

          capabilities: {}

          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data

          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: dbPassword

            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: dbUsername

            - name: POSTGRESQL_DATABASE
              value: nextcloud

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 1

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-{{ template "nextcloud.fullname" . }}
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-{{ template "nextcloud.fullname" . }}
        - name: config
          configMap:
            name: {{ template "nextcloud.fullname" . }}
            items:
              - key: s3-config
                path: s3.config.php
              - key: auth-config
                path: auth.config.php
