---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nginx-nextcloud-{{ template "nextcloud.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "nextcloud.name" . }}
spec:
  tag:
    name: latest
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nginx-{{ template "nextcloud.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "nextcloud.name" . }}
spec:
  dockerImageRepository: "docker.io/nginx"
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: nginx:latest
      referencePolicy:
        type: Source
