---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "nextcloud.name" . }}
spec:
  host: {{ .Values.nextcloud.TrustedDomains }}
  to:
    kind: Service
    name: {{ template "nextcloud.fullname" . }}
  port:
    targetPort: 8080
