---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "nextcloud.name" . }}
type: Opaque
stringData:
  dbUsername: {{ .Values.nextcloud.Db.User | default "nextcloud" | quote }}
  {{- if .Values.nextcloud.Db.Password }}
  dbPassword: {{ .Values.nextcloud.Db.Password | b64enc | quote }}
  {{- else }}
  dbPassword: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  appUsername: {{ .Values.nextcloud.Admin.User | default "nextcloud" | quote }}
  appPassword: {{ .Values.nextcloud.Admin.Password | default "cloudnext" | quote }}
