---
kind: Secret
apiVersion: v1
metadata:
  name: ${APPLICATION_NAME}-secrets
  labels:
    app: ${APPLICATION_NAME}
type: Opaque
stringData:
  dbUsername: ${NEXTCLOUD_DB_USER}
  dbPassword: ${NEXTCLOUD_DB_PASSWORD}
  appUsername: ${NEXTCLOUD_ADMIN_USER}
  appPassword: ${NEXTCLOUD_ADMIN_PASSWORD}
